# CobbleBot AHK Macro Generator
# Copyright (C) 2020, OctoAndri
# https://github.com/andrigamerita/CobbleBot
# Licensed under the GPLv3 license:
# https://www.gnu.org/licenses/gpl-3.0.en.html

import argparse
import os
from os.path import exists

ap = argparse.ArgumentParser()
ap.add_argument("-b", "--block",
    help="Specifies the amount of blocks that have already been generated; default is 0")
ap.add_argument("-c", "--click",
    help="Specifies the button that acts as the Place/Interact; default is Right Mouse ({RButton})")
ap.add_argument("-l", "--lava",
    help="Specifies the button that selects Lava in the hotbar; default is Numrow 8 (8)")
ap.add_argument("-w", "--water",
    help="Specifies the button that selects Water in the hotbar; default is Numrow 9 (9)")
ap.add_argument("-s", "--stop",
    help="Specifies the button that Stops or Exits the script; default is LAlt+S (!S)")
args = ap.parse_args()

loopgen = int(0)
loopweight = int(90)
maxblocks = int(255)
clickbtn = str("{RButton}")
lavabtn = str("8")
waterbtn = str("9")
stopbtn = str("!S")
usedoptions = int(0)

if (str(args.block) != "None"):
    loopgen = int(args.block)
    usedoptions = int(1)
if (str(args.click) != "None"):
    clickbtn = str(args.click)
    usedoptions = int(1)
if (str(args.lava) != "None"):
    lavabtn = str(args.lava)
    usedoptions = int(1)
if (str(args.water) != "None"):
    waterbtn = str(args.water)
    usedoptions = int(1)
if (str(args.stop) != "None"):
    stopbtn = str(args.stop)
    usedoptions = int(1)

if exists("CobbleBotAHK.ahk"):
    os.remove("CobbleBotAHK.ahk")
fh = open("CobbleBotAHK.ahk", "a")

fh.write("; Generated by the CobbleBot AHK Macro Generator\n; Copyright 2020, OctoAndri\n; https://github.com/andrigamerita/CobbleBot\n; Licensed under the GPLv3 license:\n; https://www.gnu.org/licenses/gpl-3.0.en.html")
fh.write("\n")
fh.write("\n#NoEnv")
fh.write("\nSendMode Input")
fh.write("\nSetWorkingDir %A_ScriptDir%")
fh.write("\nSleep, 3000")

if (loopgen > 0):
    loopweight = (90 + (loopgen * 120))

while (loopgen < maxblocks):
    fh.write("\n")
    fh.write("\nSend " + lavabtn)
    fh.write("\nSend " + clickbtn)
    fh.write("\nSleep, 90 * 0.05 * 1000")
    fh.write("\nSend " + clickbtn)
    fh.write("\nSleep, " + str(loopweight) + " * 0.05 * 1000")
    fh.write("\nSend " + waterbtn)
    fh.write("\nSend " + clickbtn)
    fh.write("\nSleep, 15 * 0.05 * 1000")
    fh.write("\nSend " + clickbtn)
    fh.write("\nSleep, 2000")
    loopweight = (loopweight + 120)
    loopgen = (loopgen + 1)
    
fh.write("\n")
fh.write("\n" + stopbtn + "::ExitApp")
    
fh.close()

if (usedoptions != int(1)):
    print("\nNOTE: You started the script with default settings.\nStart it with flag -h to see all the available options.")
print("\nScript completed.\nCobbleBotAHK.ahk saved in the current directory.")